---
- name: Sett riktig tidssone
  hosts: IOS_XE_switcher
  gather_facts: false


  tasks: 

    - name: Sett tidssone
      cisco.ios.ios_config:
        lines:
          - clock timezone CET 1
          - clock summer-time CEST recurring last Sun Mar 2:00 last Sun Oct 3:00

